apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  params:
  - name: buildRevision
    value: 'e99b15f88b47b1d25255f1be8d4fd56f397e3d26'
  - name: appGitUrl
    value: 'https://github.com/mytestlab123/scalable-coffee-shop'
#    value: 'git@github.com:mytestlab123/scalable-coffee-shop.git'
  - name: configGitUrl
    value: 'git@github.com:mytestlab123/coffee-testing-config.git'
  - name: appImage
    value: 'amitkarpe/tkn1'
  workspaces:
  - name: app-source
    emptyDir: {}
  - name: config-source
    emptyDir: {}
---
